### ISSUE TITLE
[Build Error]  cannot open linker script file ..\Debug_STM32F103C8_FLASH.ld: No such file or directory 

### ISSUE THREAD

**Issue by tongtybj** [tongtybj/hydrus#5]
@chibi314 

master ブランチをビルドすると以下のエラーがでます。
```
c:/program files (x86)/atollic/truestudio for arm 6.0.0/armtools/bin/../lib/gcc/arm-atollic-eabi/5.3.1/../../../../arm-atollic-eabi/bin/ld.exe: cannot open linker script file ..\Debug_STM32F103C8_FLASH.ld: No such file or directory
collect2.exe: error: ld returned 1 exit status
```

.gitignoreでは/Debugが無視されていることから、
以前話したコンパイル時はApplication下ではなく、
Debug下のソースコードが参照されている問題と絡んでいると推測しています。

**Comment by tongtybj** [comment]
@chibi314 

.project内のSTM32F103C8_FLASH.ldの指定場所を以下のように変更したら、ビルドできました。
https://github.com/tongtybj/hydrus/commit/c650c2c804662f0ed02069d8458dacd90130ca45#diff-473be75615088a3a7e221b84bfc60946L127

**Comment by chibi314** [comment]
@tongtybj その変更をしてこちらでも大丈夫でしたのでこれでいきましょう。ご迷惑おかけしました。
